// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4n-J9FrtjhkQ_wYhb5mA9bIVJhWCSQcQ',
    appId: '1:1068264413537:web:12ca293528fc33605e0d20',
    messagingSenderId: '1068264413537',
    projectId: 'dbpractice-60955',
    authDomain: 'dbpractice-60955.firebaseapp.com',
    storageBucket: 'dbpractice-60955.firebasestorage.app',
    measurementId: 'G-5EGJ0H0RT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn8gCd7hylo4pi0FwnaITLyHyFx-zphPA',
    appId: '1:1068264413537:android:fc81800d44bef3535e0d20',
    messagingSenderId: '1068264413537',
    projectId: 'dbpractice-60955',
    storageBucket: 'dbpractice-60955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUUjzD19HMjUG9mQWKuG2cr4kRvWBrwvk',
    appId: '1:1068264413537:ios:c94c04d7a209514c5e0d20',
    messagingSenderId: '1068264413537',
    projectId: 'dbpractice-60955',
    storageBucket: 'dbpractice-60955.firebasestorage.app',
    iosBundleId: 'com.example.dbpractice',
  );
}
